# Site settings
title: Trendo Web, Web marketing, Grow Hacking crafted with care
email:
description: A web journal about web, business, marketing, tech, hacks to be free

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://trentoweb.github.io" # the base hostname & protocol for your site

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: trendo-web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
